-- Additive independent LandOS catalog review; no changes to MaxQI.
begin;
alter table public.layer_catalog add column release_status text not null default 'beta'
 check (release_status in ('verified','beta','disabled','deprecated'));
alter table public.layer_catalog add column release_checklist jsonb not null default '{}'::jsonb;
-- Existing sources remain usable; beta distinguishes technical verification from a complete launch review.
insert into public.layer_catalog(id,name,state,category,provider,service_url,renderer,layer_ids,description,attribution,usage_notes,source_url,update_frequency,premium_tier,min_zoom,enabled,release_status,release_checklist) values
('nsw-fsr','NSW floor space ratio','NSW','Planning','NSW Department of Planning, Housing and Infrastructure','https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer','arcgis_export','1','Maximum mapped floor space ratio designated by the applicable EPI. Coverage depends on instrument mapping; not development entitlement.','© State Government of NSW and NSW Department of Planning, Housing and Infrastructure 2018','Creative Commons Attribution as listed by the official dataset. Indicative mapping; consult current instrument, exceptions and consent authority. Disabled pending verified data-dictionary special/missing-value interpretation.','https://www.planningportal.nsw.gov.au/opendata/dataset/environmental-planning-instrument-floor-space-ratio','Weekly (dataset metadata; service currency may differ)','pro',9,false,'disabled',
'{"reviewed_on":"2026-10-07","provider":"NSW DPHI","endpoint_layer":1,"coverage":"Mapped applicable NSW EPIs, not universal development entitlement","geometry_type":"Polygon","legend":"Official MapServer legend returned HTTP502 during latest review; not released","license":"Creative Commons Attribution (official dataset)","license_url":"http://www.opendefinition.org/licenses/cc-by","attribution":"Official dataset attribution retained","update_frequency":"Weekly","known_limitation":"Missing/special values cannot be interpreted as no restriction","property_intersection_support":"Not released; special-value interpretation gate","release_blocker":"Official data dictionary download redirected to HTTP403 during review; finish missing/special-value and legend review before enablement"}'::jsonb),
('nsw-height','NSW height of buildings','NSW','Planning','NSW Department of Planning, Housing and Infrastructure','https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer','arcgis_export','5','Maximum mapped building height designated by the applicable EPI. Height value, units, metres and reduced-level fields require the instrument and data dictionary.','© State Government of NSW and NSW Department of Planning, Housing and Infrastructure 2018','Creative Commons Attribution as listed by the official dataset. Indicative mapping; consult current instrument and units. Disabled pending verified data-dictionary special/missing-value interpretation.','https://www.planningportal.nsw.gov.au/opendata/dataset/environmental-planning-instrument-height-of-buildings-hob','Weekly (dataset metadata; service currency may differ)','pro',9,false,'disabled',
'{"reviewed_on":"2026-10-07","provider":"NSW DPHI","endpoint_layer":5,"coverage":"Mapped applicable NSW EPIs, not universal development entitlement","geometry_type":"Polygon","legend":"Official MapServer legend returned HTTP502 during latest review; not released","license":"Creative Commons Attribution (official dataset)","license_url":"http://www.opendefinition.org/licenses/cc-by","attribution":"Official dataset attribution retained","update_frequency":"Weekly","known_limitation":"Height units/metres/reduced-level and missing/special values require interpretation; no result is not unrestricted height","property_intersection_support":"Not released; special-value interpretation gate","release_blocker":"Official data dictionary download redirected to HTTP403 during review; finish missing/special-value and legend review before enablement"}'::jsonb)
on conflict(id) do nothing;
commit;
