-- Independent Land Banker only. Never apply to MaxQI or PROS.
begin;
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', created_at timestamptz not null default now());
create table public.workspaces(id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 1 and 120), personal_owner_id uuid unique references auth.users(id), created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(id,personal_owner_id));
create table public.workspace_memberships(workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in ('owner','admin','editor','viewer')), status text not null default 'active' check(status in ('active','invited','suspended')), created_at timestamptz not null default now(), primary key(workspace_id,user_id));
create index memberships_user_idx on public.workspace_memberships(user_id,workspace_id) where status='active';
-- Non-exposed, fixed-search-path lookup to avoid recursive membership policies.
-- This deliberately returns permissions only for auth.uid(), never a caller-supplied user.
create function private.has_workspace_role(w uuid, permitted text[]) returns boolean language sql stable security definer set search_path='' as $$
 select auth.uid() is not null and exists(select 1 from public.workspace_memberships m where m.workspace_id=w and m.user_id=auth.uid() and m.status='active' and m.role=any(permitted));
$$;
revoke all on function private.has_workspace_role(uuid,text[]) from public,anon;
grant execute on function private.has_workspace_role(uuid,text[]) to authenticated;
-- Trigger-only bootstrap. Role is a constant; user metadata is display-only.
create function private.bootstrap_user() returns trigger language plpgsql security definer set search_path='' as $$
declare w uuid; display text;
begin
 display := left(coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Personal'),80);
 insert into public.profiles(id,display_name) values(new.id,display);
 insert into public.workspaces(name,personal_owner_id,created_by) values(display || '''s Workspace',new.id,new.id) returning id into w;
 insert into public.workspace_memberships(workspace_id,user_id,role,status) values(w,new.id,'owner','active');
 return new;
end;
$$;
revoke all on function private.bootstrap_user() from public,anon,authenticated;
create trigger land_banker_user_created after insert on auth.users for each row execute function private.bootstrap_user();
create table public.land_parcels(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),title text not null check(length(title) between 1 and 160),latitude double precision check(latitude between -90 and 90),longitude double precision check(longitude between -180 and 180),geometry jsonb,hectares numeric,status text not null default 'research',notes text,metadata jsonb not null default '{}',created_by uuid references auth.users(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id));
create table public.field_observations(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),title text not null check(length(title) between 1 and 160),notes text,latitude double precision not null check(latitude between -90 and 90),longitude double precision not null check(longitude between -180 and 180),observed_at timestamptz not null default now(),linked_parcel_id uuid,metadata jsonb not null default '{}',created_by uuid references auth.users(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id),foreign key(workspace_id,linked_parcel_id) references public.land_parcels(workspace_id,id));
create table public.field_observation_media(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),observation_id uuid not null,mime_type text not null,original_filename text not null,size_bytes bigint not null check(size_bytes>=0),storage_path text unique,captured_at timestamptz,upload_status text not null default 'pending' check(upload_status in ('pending','uploading','uploaded','failed','legacy_pending')),metadata jsonb not null default '{}',created_by uuid references auth.users(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id),foreign key(workspace_id,observation_id) references public.field_observations(workspace_id,id) on delete cascade,check(storage_path is null or storage_path like workspace_id::text || '/' || observation_id::text || '/' || id::text || '.%'));
create table public.spatial_layers(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),name text not null,layer_kind text not null default 'geojson',geojson jsonb,layer_data jsonb not null default '{}',metadata jsonb not null default '{}',created_by uuid references auth.users(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id));
create table public.spatial_features(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),layer_id uuid not null,feature jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id),foreign key(workspace_id,layer_id) references public.spatial_layers(workspace_id,id) on delete cascade);
create table public.saved_views(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),name text not null,view jsonb not null,created_by uuid references auth.users(id) default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,id));
create table public.share_links(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),created_by uuid not null references auth.users(id) default auth.uid(),token_hash text not null unique check(token_hash ~ '^[0-9a-f]{64}$'),resource_type text not null check(resource_type in ('parcel','parcels','spatial_layer','saved_view','subset')),resource_id uuid,resource_ids uuid[] not null default '{}',permissions text not null default 'read' check(permissions='read'),expires_at timestamptz not null,revoked_at timestamptz,created_at timestamptz not null default now());
create table public.migration_mappings(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),source_system text not null,source_table text not null,legacy_id text not null,target_table text not null,target_id uuid not null,source_hash text not null,imported_at timestamptz not null default now(),unique(workspace_id,source_system,source_table,legacy_id));
create function private.lock_workspace() returns trigger language plpgsql set search_path='' as $$begin if new.workspace_id<>old.workspace_id then raise exception 'workspace_id is immutable';end if;new.updated_at=now();return new;end;$$;
revoke all on function private.lock_workspace() from public;
alter table public.profiles enable row level security;
revoke all on public.profiles from anon,authenticated;
grant all on public.profiles to service_role;
alter table public.workspaces enable row level security;
revoke all on public.workspaces from anon,authenticated;
grant all on public.workspaces to service_role;
alter table public.workspace_memberships enable row level security;
revoke all on public.workspace_memberships from anon,authenticated;
grant all on public.workspace_memberships to service_role;
alter table public.land_parcels enable row level security;
revoke all on public.land_parcels from anon,authenticated;
grant all on public.land_parcels to service_role;
alter table public.field_observations enable row level security;
revoke all on public.field_observations from anon,authenticated;
grant all on public.field_observations to service_role;
alter table public.field_observation_media enable row level security;
revoke all on public.field_observation_media from anon,authenticated;
grant all on public.field_observation_media to service_role;
alter table public.spatial_layers enable row level security;
revoke all on public.spatial_layers from anon,authenticated;
grant all on public.spatial_layers to service_role;
alter table public.spatial_features enable row level security;
revoke all on public.spatial_features from anon,authenticated;
grant all on public.spatial_features to service_role;
alter table public.saved_views enable row level security;
revoke all on public.saved_views from anon,authenticated;
grant all on public.saved_views to service_role;
alter table public.share_links enable row level security;
revoke all on public.share_links from anon,authenticated;
grant all on public.share_links to service_role;
alter table public.migration_mappings enable row level security;
revoke all on public.migration_mappings from anon,authenticated;
grant all on public.migration_mappings to service_role;
grant select,update on public.profiles to authenticated;
create policy own_profile_read on public.profiles for select to authenticated using(id=auth.uid());
create policy own_profile_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
grant select on public.workspaces,public.workspace_memberships to authenticated;
create policy workspace_read on public.workspaces for select to authenticated using(private.has_workspace_role(id,array['owner','admin','editor','viewer']));
create policy membership_read on public.workspace_memberships for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
grant select,insert,update,delete on public.land_parcels to authenticated;
create index land_parcels_workspace_idx on public.land_parcels(workspace_id);
create policy member_read on public.land_parcels for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.land_parcels for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.land_parcels for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.land_parcels for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.land_parcels for each row execute function private.lock_workspace();
grant select,insert,update,delete on public.field_observations to authenticated;
create index field_observations_workspace_idx on public.field_observations(workspace_id);
create policy member_read on public.field_observations for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.field_observations for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.field_observations for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.field_observations for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.field_observations for each row execute function private.lock_workspace();
grant select,insert,update,delete on public.field_observation_media to authenticated;
create index field_observation_media_workspace_idx on public.field_observation_media(workspace_id);
create policy member_read on public.field_observation_media for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.field_observation_media for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.field_observation_media for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.field_observation_media for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.field_observation_media for each row execute function private.lock_workspace();
grant select,insert,update,delete on public.spatial_layers to authenticated;
create index spatial_layers_workspace_idx on public.spatial_layers(workspace_id);
create policy member_read on public.spatial_layers for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.spatial_layers for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.spatial_layers for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.spatial_layers for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.spatial_layers for each row execute function private.lock_workspace();
grant select,insert,update,delete on public.spatial_features to authenticated;
create index spatial_features_workspace_idx on public.spatial_features(workspace_id);
create policy member_read on public.spatial_features for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.spatial_features for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.spatial_features for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.spatial_features for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.spatial_features for each row execute function private.lock_workspace();
grant select,insert,update,delete on public.saved_views to authenticated;
create index saved_views_workspace_idx on public.saved_views(workspace_id);
create policy member_read on public.saved_views for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor','viewer']));
create policy member_insert on public.saved_views for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy member_update on public.saved_views for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin','editor'])) with check(private.has_workspace_role(workspace_id,array['owner','admin','editor']));
create policy manager_delete on public.saved_views for delete to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create trigger immutable_workspace before update on public.saved_views for each row execute function private.lock_workspace();
grant select,insert,update on public.share_links to authenticated;
create policy manager_share_read on public.share_links for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
create policy manager_share_insert on public.share_links for insert to authenticated with check(private.has_workspace_role(workspace_id,array['owner','admin']) and created_by=auth.uid());
-- Only revoke can be updated by clients; scope and token immutable.
revoke update on public.share_links from authenticated;
grant update(revoked_at) on public.share_links to authenticated;
create policy manager_share_revoke on public.share_links for update to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin'])) with check(private.has_workspace_role(workspace_id,array['owner','admin']));
grant select on public.migration_mappings to authenticated;
create policy manager_mapping_read on public.migration_mappings for select to authenticated using(private.has_workspace_role(workspace_id,array['owner','admin']));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('field-media','field-media',false,26214400,array['image/jpeg','image/png','image/heic']) on conflict(id) do nothing;
-- Require a registered media row matching this path, not merely a workspace prefix.
create policy field_media_read on storage.objects for select to authenticated using(bucket_id='field-media' and exists(select 1 from public.field_observation_media m where m.storage_path=name and private.has_workspace_role(m.workspace_id,array['owner','admin','editor','viewer'])));
create policy field_media_insert on storage.objects for insert to authenticated with check(bucket_id='field-media' and exists(select 1 from public.field_observation_media m where m.storage_path=name and private.has_workspace_role(m.workspace_id,array['owner','admin','editor'])));
create policy field_media_update on storage.objects for update to authenticated using(bucket_id='field-media' and exists(select 1 from public.field_observation_media m where m.storage_path=name and private.has_workspace_role(m.workspace_id,array['owner','admin','editor']))) with check(bucket_id='field-media' and exists(select 1 from public.field_observation_media m where m.storage_path=name and private.has_workspace_role(m.workspace_id,array['owner','admin','editor'])));
create policy field_media_delete on storage.objects for delete to authenticated using(bucket_id='field-media' and exists(select 1 from public.field_observation_media m where m.storage_path=name and private.has_workspace_role(m.workspace_id,array['owner','admin'])));
commit;
